#   Add your code here and add comments to your code 
#   to describe what each section of code is doing

import turtle as trtl
painter = trtl.Turtle()
trtl.Screen().bgcolor("green") 
painter.pencolor("white")

painter.pensize(3)

painter.penup()
painter.goto(0,-30)
painter.pendown()
painter.circle(30)

painter.penup()
painter.goto(-150,-80)
painter.pendown()
painter.forward(300)
painter.left(90)
painter.forward(160)
painter.left(90)
painter.forward(300)
painter.left(90)
painter.forward(160)

painter.penup()
painter.goto(0,80)
painter.pendown()
painter.forward(160)

painter.penup()
painter.goto(-150,-50)
painter.pendown()
painter.left(90)
painter.forward(60)
painter.left(90)
painter.forward(100)
painter.left(90)
painter.forward(60)

painter.penup()
painter.goto(150,-50)
painter.pendown()
painter.forward(60)
painter.right(90)
painter.forward(100)
painter.right(90)
painter.forward(60)

painter.penup()
painter.goto(-150,-30)
painter.pendown()
painter.forward(25)
painter.left(90)
painter.forward(60)
painter.left(90)
painter.forward(25)

painter.penup()
painter.goto(150,-30)
painter.pendown()
painter.forward(25)
painter.right(90)
painter.forward(60)
painter.right(90)
painter.forward(25)

painter.penup()
painter.goto(-1000,-1000)